# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug


---

# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysqlservice  # DNS name
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP # Note: The default Service type in Kubernetes, if no type is specified, is "ClusterIP".
  ports:
    - name: mysql
      port: 3306
  selector:       # mysql Pod Should contain same labels
    app: mysql
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant


---

# Configure 'StatefulSet' of mysql server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysqlservice
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: conf
              mountPath: /etc/mysql/conf.d
      volumes: 
        - name: conf
          emptyDir: {}
        - name: config-map
          configMap: 
            name: mysql    
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: gcp-storage-class
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

