apiVersion: v1
kind: Service
metadata:
  name: k8sonespringbootapp-service
spec:
  selector:
    app: k8sonespringbootapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer